/*
 * SupeScrapbook
 *
 * The API for the SupeScrapbook
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace SupesScrapbook.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Appearance : IEquatable<Appearance>
    {
        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        /* <example>Male</example> */
        [DataMember(Name="gender", EmitDefaultValue=false)]
        public string Gender { get; set; }

        /// <summary>
        /// Gets or Sets Race
        /// </summary>
        /* <example>Human</example> */
        [DataMember(Name="race", EmitDefaultValue=false)]
        public string Race { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        /* <example>[&quot;6&#39;8&quot;,&quot;203cm&quot;]</example> */
        [DataMember(Name="height", EmitDefaultValue=false)]
        public List<string> Height { get; set; }

        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        /* <example>[&quot;980 lb&quot;,&quot;441 kg&quot;]</example> */
        [DataMember(Name="weight", EmitDefaultValue=false)]
        public List<string> Weight { get; set; }

        /// <summary>
        /// Gets or Sets EyeColor
        /// </summary>
        /* <example>Yellow</example> */
        [DataMember(Name="eyeColor", EmitDefaultValue=false)]
        public string EyeColor { get; set; }

        /// <summary>
        /// Gets or Sets HairColor
        /// </summary>
        /* <example>No Hair</example> */
        [DataMember(Name="hairColor", EmitDefaultValue=false)]
        public string HairColor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Appearance {\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  Race: ").Append(Race).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  EyeColor: ").Append(EyeColor).Append("\n");
            sb.Append("  HairColor: ").Append(HairColor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Appearance)obj);
        }

        /// <summary>
        /// Returns true if Appearance instances are equal
        /// </summary>
        /// <param name="other">Instance of Appearance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Appearance other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Gender == other.Gender ||
                    Gender != null &&
                    Gender.Equals(other.Gender)
                ) && 
                (
                    Race == other.Race ||
                    Race != null &&
                    Race.Equals(other.Race)
                ) && 
                (
                    Height == other.Height ||
                    Height != null &&
                    other.Height != null &&
                    Height.SequenceEqual(other.Height)
                ) && 
                (
                    Weight == other.Weight ||
                    Weight != null &&
                    other.Weight != null &&
                    Weight.SequenceEqual(other.Weight)
                ) && 
                (
                    EyeColor == other.EyeColor ||
                    EyeColor != null &&
                    EyeColor.Equals(other.EyeColor)
                ) && 
                (
                    HairColor == other.HairColor ||
                    HairColor != null &&
                    HairColor.Equals(other.HairColor)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Gender != null)
                    hashCode = hashCode * 59 + Gender.GetHashCode();
                    if (Race != null)
                    hashCode = hashCode * 59 + Race.GetHashCode();
                    if (Height != null)
                    hashCode = hashCode * 59 + Height.GetHashCode();
                    if (Weight != null)
                    hashCode = hashCode * 59 + Weight.GetHashCode();
                    if (EyeColor != null)
                    hashCode = hashCode * 59 + EyeColor.GetHashCode();
                    if (HairColor != null)
                    hashCode = hashCode * 59 + HairColor.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Appearance left, Appearance right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Appearance left, Appearance right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
