/*
 * SupeScrapbook
 *
 * The API for the SupeScrapbook
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace SupesScrapbook.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Biography : IEquatable<Biography>
    {
        /// <summary>
        /// Gets or Sets FullName
        /// </summary>
        /* <example>Richard Milhouse Jones</example> */
        [DataMember(Name="fullName", EmitDefaultValue=false)]
        public string FullName { get; set; }

        /// <summary>
        /// Gets or Sets AlterEgos
        /// </summary>
        /* <example>No alter egos found.</example> */
        [DataMember(Name="alterEgos", EmitDefaultValue=false)]
        public string AlterEgos { get; set; }

        /// <summary>
        /// Gets or Sets Aliases
        /// </summary>
        /* <example>[&quot;Rick Jones&quot;]</example> */
        [DataMember(Name="aliases", EmitDefaultValue=false)]
        public List<string> Aliases { get; set; }

        /// <summary>
        /// Gets or Sets PlaceOfBirth
        /// </summary>
        /* <example>Scarsdale, Arizona</example> */
        [DataMember(Name="placeOfBirth", EmitDefaultValue=false)]
        public string PlaceOfBirth { get; set; }

        /// <summary>
        /// Gets or Sets FirstAppearance
        /// </summary>
        /* <example>Hulk Vol 2 #2 (April, 2008) (as A-Bomb)</example> */
        [DataMember(Name="firstAppearance", EmitDefaultValue=false)]
        public string FirstAppearance { get; set; }

        /// <summary>
        /// Gets or Sets Publisher
        /// </summary>
        /* <example>Marvel Comics</example> */
        [DataMember(Name="publisher", EmitDefaultValue=false)]
        public string Publisher { get; set; }

        /// <summary>
        /// Gets or Sets Alignment
        /// </summary>
        /* <example>good</example> */
        [DataMember(Name="alignment", EmitDefaultValue=false)]
        public string Alignment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Biography {\n");
            sb.Append("  FullName: ").Append(FullName).Append("\n");
            sb.Append("  AlterEgos: ").Append(AlterEgos).Append("\n");
            sb.Append("  Aliases: ").Append(Aliases).Append("\n");
            sb.Append("  PlaceOfBirth: ").Append(PlaceOfBirth).Append("\n");
            sb.Append("  FirstAppearance: ").Append(FirstAppearance).Append("\n");
            sb.Append("  Publisher: ").Append(Publisher).Append("\n");
            sb.Append("  Alignment: ").Append(Alignment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Biography)obj);
        }

        /// <summary>
        /// Returns true if Biography instances are equal
        /// </summary>
        /// <param name="other">Instance of Biography to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Biography other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FullName == other.FullName ||
                    FullName != null &&
                    FullName.Equals(other.FullName)
                ) && 
                (
                    AlterEgos == other.AlterEgos ||
                    AlterEgos != null &&
                    AlterEgos.Equals(other.AlterEgos)
                ) && 
                (
                    Aliases == other.Aliases ||
                    Aliases != null &&
                    other.Aliases != null &&
                    Aliases.SequenceEqual(other.Aliases)
                ) && 
                (
                    PlaceOfBirth == other.PlaceOfBirth ||
                    PlaceOfBirth != null &&
                    PlaceOfBirth.Equals(other.PlaceOfBirth)
                ) && 
                (
                    FirstAppearance == other.FirstAppearance ||
                    FirstAppearance != null &&
                    FirstAppearance.Equals(other.FirstAppearance)
                ) && 
                (
                    Publisher == other.Publisher ||
                    Publisher != null &&
                    Publisher.Equals(other.Publisher)
                ) && 
                (
                    Alignment == other.Alignment ||
                    Alignment != null &&
                    Alignment.Equals(other.Alignment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FullName != null)
                    hashCode = hashCode * 59 + FullName.GetHashCode();
                    if (AlterEgos != null)
                    hashCode = hashCode * 59 + AlterEgos.GetHashCode();
                    if (Aliases != null)
                    hashCode = hashCode * 59 + Aliases.GetHashCode();
                    if (PlaceOfBirth != null)
                    hashCode = hashCode * 59 + PlaceOfBirth.GetHashCode();
                    if (FirstAppearance != null)
                    hashCode = hashCode * 59 + FirstAppearance.GetHashCode();
                    if (Publisher != null)
                    hashCode = hashCode * 59 + Publisher.GetHashCode();
                    if (Alignment != null)
                    hashCode = hashCode * 59 + Alignment.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Biography left, Biography right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Biography left, Biography right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
