/*
 * SupeScrapbook
 *
 * The API for the SupeScrapbook
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace SupesScrapbook.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Connections : IEquatable<Connections>
    {
        /// <summary>
        /// Gets or Sets GroupAffiliation
        /// </summary>
        /* <example>Hulk Family; Avengers (honorary member)</example> */
        [DataMember(Name="groupAffiliation", EmitDefaultValue=false)]
        public string GroupAffiliation { get; set; }

        /// <summary>
        /// Gets or Sets Relatives
        /// </summary>
        /* <example>Marlo Chandler-Jones (wife)</example> */
        [DataMember(Name="relatives", EmitDefaultValue=false)]
        public string Relatives { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Connections {\n");
            sb.Append("  GroupAffiliation: ").Append(GroupAffiliation).Append("\n");
            sb.Append("  Relatives: ").Append(Relatives).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Connections)obj);
        }

        /// <summary>
        /// Returns true if Connections instances are equal
        /// </summary>
        /// <param name="other">Instance of Connections to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Connections other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    GroupAffiliation == other.GroupAffiliation ||
                    GroupAffiliation != null &&
                    GroupAffiliation.Equals(other.GroupAffiliation)
                ) && 
                (
                    Relatives == other.Relatives ||
                    Relatives != null &&
                    Relatives.Equals(other.Relatives)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (GroupAffiliation != null)
                    hashCode = hashCode * 59 + GroupAffiliation.GetHashCode();
                    if (Relatives != null)
                    hashCode = hashCode * 59 + Relatives.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Connections left, Connections right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Connections left, Connections right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
