/*
 * SupeScrapbook
 *
 * The API for the SupeScrapbook
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;


namespace SupesScrapbook.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Images : IEquatable<Images>
    {
        /// <summary>
        /// Gets or Sets Xs
        /// </summary>
        /* <example>https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/xs/1-a-bomb.jpg</example> */
        [DataMember(Name="xs", EmitDefaultValue=false)]
        public string Xs { get; set; }

        /// <summary>
        /// Gets or Sets Sm
        /// </summary>
        /* <example>https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/sm/1-a-bomb.jpg</example> */
        [DataMember(Name="sm", EmitDefaultValue=false)]
        public string Sm { get; set; }

        /// <summary>
        /// Gets or Sets Md
        /// </summary>
        /* <example>https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/1-a-bomb.jpg</example> */
        [DataMember(Name="md", EmitDefaultValue=false)]
        public string Md { get; set; }

        /// <summary>
        /// Gets or Sets Lg
        /// </summary>
        /* <example>https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/lg/1-a-bomb.jpg</example> */
        [DataMember(Name="lg", EmitDefaultValue=false)]
        public string Lg { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Images {\n");
            sb.Append("  Xs: ").Append(Xs).Append("\n");
            sb.Append("  Sm: ").Append(Sm).Append("\n");
            sb.Append("  Md: ").Append(Md).Append("\n");
            sb.Append("  Lg: ").Append(Lg).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Images)obj);
        }

        /// <summary>
        /// Returns true if Images instances are equal
        /// </summary>
        /// <param name="other">Instance of Images to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Images other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Xs == other.Xs ||
                    Xs != null &&
                    Xs.Equals(other.Xs)
                ) && 
                (
                    Sm == other.Sm ||
                    Sm != null &&
                    Sm.Equals(other.Sm)
                ) && 
                (
                    Md == other.Md ||
                    Md != null &&
                    Md.Equals(other.Md)
                ) && 
                (
                    Lg == other.Lg ||
                    Lg != null &&
                    Lg.Equals(other.Lg)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Xs != null)
                    hashCode = hashCode * 59 + Xs.GetHashCode();
                    if (Sm != null)
                    hashCode = hashCode * 59 + Sm.GetHashCode();
                    if (Md != null)
                    hashCode = hashCode * 59 + Md.GetHashCode();
                    if (Lg != null)
                    hashCode = hashCode * 59 + Lg.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Images left, Images right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Images left, Images right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
