/*
 * SupeScrapbook
 *
 * The API for the SupeScrapbook
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;


namespace SupesScrapbook.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Powerstats : IEquatable<Powerstats>
    {
        /// <summary>
        /// Gets or Sets Intelligence
        /// </summary>
        /* <example>38</example> */
        [DataMember(Name="intelligence", EmitDefaultValue=true)]
        public decimal Intelligence { get; set; }

        /// <summary>
        /// Gets or Sets Strength
        /// </summary>
        /* <example>100</example> */
        [DataMember(Name="strength", EmitDefaultValue=true)]
        public decimal Strength { get; set; }

        /// <summary>
        /// Gets or Sets Speed
        /// </summary>
        /* <example>17</example> */
        [DataMember(Name="speed", EmitDefaultValue=false)]
        public string Speed { get; set; }

        /// <summary>
        /// Gets or Sets Durability
        /// </summary>
        /* <example>80</example> */
        [DataMember(Name="durability", EmitDefaultValue=true)]
        public decimal Durability { get; set; }

        /// <summary>
        /// Gets or Sets Power
        /// </summary>
        /* <example>24</example> */
        [DataMember(Name="power", EmitDefaultValue=true)]
        public decimal Power { get; set; }

        /// <summary>
        /// Gets or Sets Combat
        /// </summary>
        /* <example>64</example> */
        [DataMember(Name="combat", EmitDefaultValue=true)]
        public decimal Combat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Powerstats {\n");
            sb.Append("  Intelligence: ").Append(Intelligence).Append("\n");
            sb.Append("  Strength: ").Append(Strength).Append("\n");
            sb.Append("  Speed: ").Append(Speed).Append("\n");
            sb.Append("  Durability: ").Append(Durability).Append("\n");
            sb.Append("  Power: ").Append(Power).Append("\n");
            sb.Append("  Combat: ").Append(Combat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Powerstats)obj);
        }

        /// <summary>
        /// Returns true if Powerstats instances are equal
        /// </summary>
        /// <param name="other">Instance of Powerstats to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Powerstats other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Intelligence == other.Intelligence ||
                    
                    Intelligence.Equals(other.Intelligence)
                ) && 
                (
                    Strength == other.Strength ||
                    
                    Strength.Equals(other.Strength)
                ) && 
                (
                    Speed == other.Speed ||
                    Speed != null &&
                    Speed.Equals(other.Speed)
                ) && 
                (
                    Durability == other.Durability ||
                    
                    Durability.Equals(other.Durability)
                ) && 
                (
                    Power == other.Power ||
                    
                    Power.Equals(other.Power)
                ) && 
                (
                    Combat == other.Combat ||
                    
                    Combat.Equals(other.Combat)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Intelligence.GetHashCode();
                    
                    hashCode = hashCode * 59 + Strength.GetHashCode();
                    if (Speed != null)
                    hashCode = hashCode * 59 + Speed.GetHashCode();
                    
                    hashCode = hashCode * 59 + Durability.GetHashCode();
                    
                    hashCode = hashCode * 59 + Power.GetHashCode();
                    
                    hashCode = hashCode * 59 + Combat.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Powerstats left, Powerstats right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Powerstats left, Powerstats right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
