/*
 * SupeScrapbook
 *
 * The API for the SupeScrapbook
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;


namespace SupesScrapbook.Contracts.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Supe : IEquatable<Supe>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /* <example>1</example> */
        [Required]
        [DataMember(Name="id", EmitDefaultValue=true)]
        public decimal Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /* <example>A-Bomb</example> */
        [Required]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Slug
        /// </summary>
        /* <example>1-a-bomb</example> */
        [DataMember(Name="slug", EmitDefaultValue=false)]
        public string Slug { get; set; }

        /// <summary>
        /// Gets or Sets Powerstats
        /// </summary>
        [DataMember(Name="powerstats", EmitDefaultValue=false)]
        public Powerstats Powerstats { get; set; }

        /// <summary>
        /// Gets or Sets Appearance
        /// </summary>
        [DataMember(Name="appearance", EmitDefaultValue=false)]
        public Appearance Appearance { get; set; }

        /// <summary>
        /// Gets or Sets Biography
        /// </summary>
        [DataMember(Name="biography", EmitDefaultValue=false)]
        public Biography Biography { get; set; }

        /// <summary>
        /// Gets or Sets Work
        /// </summary>
        [DataMember(Name="work", EmitDefaultValue=false)]
        public Work Work { get; set; }

        /// <summary>
        /// Gets or Sets Connections
        /// </summary>
        [DataMember(Name="connections", EmitDefaultValue=false)]
        public Connections Connections { get; set; }

        /// <summary>
        /// Gets or Sets Images
        /// </summary>
        [DataMember(Name="images", EmitDefaultValue=false)]
        public Images Images { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Supe {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Slug: ").Append(Slug).Append("\n");
            sb.Append("  Powerstats: ").Append(Powerstats).Append("\n");
            sb.Append("  Appearance: ").Append(Appearance).Append("\n");
            sb.Append("  Biography: ").Append(Biography).Append("\n");
            sb.Append("  Work: ").Append(Work).Append("\n");
            sb.Append("  Connections: ").Append(Connections).Append("\n");
            sb.Append("  Images: ").Append(Images).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Supe)obj);
        }

        /// <summary>
        /// Returns true if Supe instances are equal
        /// </summary>
        /// <param name="other">Instance of Supe to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Supe other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Slug == other.Slug ||
                    Slug != null &&
                    Slug.Equals(other.Slug)
                ) && 
                (
                    Powerstats == other.Powerstats ||
                    Powerstats != null &&
                    Powerstats.Equals(other.Powerstats)
                ) && 
                (
                    Appearance == other.Appearance ||
                    Appearance != null &&
                    Appearance.Equals(other.Appearance)
                ) && 
                (
                    Biography == other.Biography ||
                    Biography != null &&
                    Biography.Equals(other.Biography)
                ) && 
                (
                    Work == other.Work ||
                    Work != null &&
                    Work.Equals(other.Work)
                ) && 
                (
                    Connections == other.Connections ||
                    Connections != null &&
                    Connections.Equals(other.Connections)
                ) && 
                (
                    Images == other.Images ||
                    Images != null &&
                    Images.Equals(other.Images)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Slug != null)
                    hashCode = hashCode * 59 + Slug.GetHashCode();
                    if (Powerstats != null)
                    hashCode = hashCode * 59 + Powerstats.GetHashCode();
                    if (Appearance != null)
                    hashCode = hashCode * 59 + Appearance.GetHashCode();
                    if (Biography != null)
                    hashCode = hashCode * 59 + Biography.GetHashCode();
                    if (Work != null)
                    hashCode = hashCode * 59 + Work.GetHashCode();
                    if (Connections != null)
                    hashCode = hashCode * 59 + Connections.GetHashCode();
                    if (Images != null)
                    hashCode = hashCode * 59 + Images.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Supe left, Supe right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Supe left, Supe right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
