/*
 * SupeScrapbook
 *
 * The API for the SupeScrapbook
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace SupesScrapbook.Contracts.Responses
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ErrorV1 : IEquatable<ErrorV1>
    {

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ErrorCodeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ErrorCodeEnum
        {
            
            /// <summary>
            /// Enum InternalErrorEnum for InternalError
            /// </summary>
            [EnumMember(Value = "InternalError")]
            InternalErrorEnum = 1
        }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [Required]
        [DataMember(Name="errorCode", EmitDefaultValue=true)]
        public ErrorCodeEnum ErrorCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ErrorV1 {\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ErrorV1)obj);
        }

        /// <summary>
        /// Returns true if ErrorV1 instances are equal
        /// </summary>
        /// <param name="other">Instance of ErrorV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ErrorV1 other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                
                    ErrorCode == other.ErrorCode ||
                    
                    ErrorCode.Equals(other.ErrorCode)
                ;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + ErrorCode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ErrorV1 left, ErrorV1 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ErrorV1 left, ErrorV1 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
